const dsaQuizData = [
    // --- 1-100 (Existing with topics) ---
    { topic: "trees", question: "What is the time complexity of searching an element in a balanced Binary Search Tree?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], answer: 2 },
    { topic: "stacks-queues", question: "Which data structure uses the LIFO (Last In First Out) principle?", options: ["Queue", "Stack", "Linked List", "Tree"], answer: 1 },
    { topic: "algorithms", question: "What is the worst-case time complexity of QuickSort?", options: ["O(n log n)", "O(n^2)", "O(n)", "O(log n)"], answer: 1 },
    { topic: "graphs", question: "Which of the following is NOT a linear data structure?", options: ["Array", "Linked List", "Stack", "Graph"], answer: 3 },
    { topic: "linked-lists", question: "What is the time complexity to insert a node at the beginning of a Singly Linked List?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], answer: 0 },
    { topic: "algorithms", question: "Which sorting algorithm is known as the fastest for small datasets?", options: ["Merge Sort", "Quick Sort", "Insertion Sort", "Heap Sort"], answer: 2 },
    { topic: "trees", question: "In a min-heap, where is the minimum element located?", options: ["Leaf node", "Middle node", "Root node", "Random node"], answer: 2 },
    { topic: "graphs", question: "Which data structure is used for Breadth First Search (BFS) of a graph?", options: ["Stack", "Queue", "Tree", "Array"], answer: 1 },
    { topic: "trees", question: "What is the maximum number of children a binary tree node can have?", options: ["1", "2", "3", "Unlimited"], answer: 1 },
    { topic: "complexity", question: "What is the time complexity of accessing an element in an array by index?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "dp", question: "Which of the following is an example of a Dynamic Programming problem?", options: ["Binary Search", "Fibonacci Series", "Bubble Sort", "Linear Search"], answer: 1 },
    { topic: "graphs", question: "What is the space complexity of an adjacency matrix for a graph with V vertices?", options: ["O(V)", "O(V + E)", "O(V^2)", "O(E)"], answer: 2 },
    { topic: "trees", question: "Which traversal of a Binary Search Tree produces sorted output?", options: ["Pre-order", "In-order", "Post-order", "Level-order"], answer: 1 },
    { topic: "algorithms", question: "What is the time complexity of Merge Sort in the worst case?", options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], answer: 1 },
    { topic: "stacks-queues", question: "Which data structure is primarily used to implement recursion?", options: ["Queue", "Stack", "Hash Table", "Linked List"], answer: 1 },
    { topic: "trees", question: "What is the height of a balanced binary tree with 'n' nodes?", options: ["O(n)", "O(log n)", "O(n log n)", "O(n^2)"], answer: 1 },
    { topic: "algorithms", question: "Which of the following is a stable sorting algorithm?", options: ["Quick Sort", "Heap Sort", "Merge Sort", "Selection Sort"], answer: 2 },
    { topic: "linked-lists", question: "In a Doubly Linked List, how many pointers does each node have?", options: ["1", "2", "3", "0"], answer: 1 },
    { topic: "trees", question: "Which data structure is used to implement a Priority Queue?", options: ["Array", "Linked List", "Heap", "Stack"], answer: 2 },
    { topic: "complexity", question: "What is the time complexity of deleting a node from a Hash Table (average case)?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "graphs", question: "Which algorithm is used to find the shortest path in a weighted graph?", options: ["Prim's", "Kruskal's", "Dijkstra's", "Huffman"], answer: 2 },
    { topic: "linked-lists", question: "What is the main advantage of a Linked List over an Array?", options: ["Faster access", "Less memory used", "Dynamic size", "Cache friendliness"], answer: 2 },
    { topic: "complexity", question: "What is a 'collision' in a Hash Table?", options: ["Two keys hashing to the same index", "Memory overflow", "Incorrect key input", "Infinite loop"], answer: 0 },
    { topic: "trees", question: "Which tree traversal uses a Queue?", options: ["In-order", "Pre-order", "Post-order", "Level-order"], answer: 3 },
    { topic: "algorithms", question: "What is the time complexity of Bubble Sort in the average case?", options: ["O(n)", "O(n log n)", "O(n^2)", "O(1)"], answer: 2 },
    { topic: "trees", question: "Which data structure represents a hierarchical relationship?", options: ["Array", "Stack", "Tree", "Queue"], answer: 2 },
    { topic: "strings", question: "Which of these is used for pattern matching in strings?", options: ["KMP Algorithm", "Dijkstra's", "Bellman-Ford", "Floyd-Warshall"], answer: 0 },
    { topic: "linked-lists", question: "What is a circular linked list?", options: ["List with no nodes", "Last node points to first node", "Middle node points to first", "First node points to itself"], answer: 1 },
    { topic: "algorithms", question: "Which approach does Merge Sort use?", options: ["Greedy", "Backtracking", "Divide and Conquer", "Dynamic Programming"], answer: 2 },
    { topic: "complexity", question: "What is the load factor of a Hash Table?", options: ["n/m (items/slots)", "m/n", "n*m", "n+m"], answer: 0 },
    { topic: "algorithms", question: "Binary Search requires the data to be:", options: ["Unsorted", "Sorted", "Large in size", "Small in size"], answer: 1 },
    { topic: "stacks-queues", question: "What is the time complexity of retrieving the top element from a Stack?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "algorithms", question: "Which of the following is a non-comparison based sort?", options: ["Quick Sort", "Merge Sort", "Radix Sort", "Shell Sort"], answer: 2 },
    { topic: "complexity", question: "What is the amortized time complexity of adding an element to a Dynamic Array?", options: ["O(n)", "O(1)", "O(log n)", "O(n^2)"], answer: 1 },
    { topic: "complexity", question: "Finding an element in an unsorted array takes:", options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"], answer: 2 },
    { topic: "graphs", question: "A graph with no cycles is called:", options: ["Complete Graph", "Tree", "Bipartite", "Directed"], answer: 1 },
    { topic: "trees", question: "What is 'Self-Balancing' in BST?", options: ["Automatic rotation to keep height small", "Deleting redundant nodes", "Sorting nodes manually", "Increasing node speed"], answer: 0 },
    { topic: "graphs", question: "Which algorithm finds the Minimum Spanning Tree?", options: ["Dijkstra's", "A*", "Prim's", "BFS"], answer: 2 },
    { topic: "stacks-queues", question: "Postfix expression for 'A + B' is:", options: ["+AB", "AB+", "A+B", "BA+"], answer: 1 },
    { topic: "algorithms", question: "What is the time complexity of Shell Sort?", options: ["O(n^2)", "Depends on gap sequence", "O(n)", "O(1)"], answer: 1 },
    { topic: "algorithms", question: "Which of these is a Greedy algorithm?", options: ["0/1 Knapsack", "Fractional Knapsack", "Matrix Chain Multiplication", "Longest Common Subsequence"], answer: 1 },
    { topic: "complexity", question: "What does 'hashing' mean?", options: ["Mapping data to a fixed-size value", "Squashing data", "Encrypting passwords only", "Sorting data using keys"], answer: 0 },
    { topic: "algorithms", question: "Space complexity of QuickSort (average case):", options: ["O(n)", "O(log n)", "O(n^2)", "O(1)"], answer: 1 },
    { topic: "stacks-queues", question: "Which data structure is best for undo operations?", options: ["Queue", "Stack", "Linked List", "Tree"], answer: 1 },
    { topic: "trees", question: "Worst-case height of a skewed binary tree with n nodes:", options: ["log n", "n", "n/2", "n^2"], answer: 1 },
    { topic: "trees", question: "B-Trees are primarily used in:", options: ["RAM", "Databases and File Systems", "Cache", "Network routing"], answer: 1 },
    { topic: "graphs", question: "A spanning tree of a graph must include:", options: ["All edges", "All vertices", "Cycles", "Weighted paths"], answer: 1 },
    { topic: "graphs", question: "Standard algorithm for finding strongly connected components:", options: ["Dijkstra's", "Kosaraju's", "Kruskal's", "Prim's"], answer: 1 },
    { topic: "trees", question: "Time complexity of Heapify operation:", options: ["O(n)", "O(log n)", "O(1)", "O(n log n)"], answer: 1 },
    { topic: "graphs", question: "In BFS, nodes are visited in order of:", options: ["Depth", "Distance from source", "Alphabetical", "Reverse"], answer: 1 },
    { topic: "trees", question: "What is a 'Deap'?", options: ["A Double-ended heap", "A deep stack", "A deleted heap", "A directed array"], answer: 0 },
    { topic: "dp", question: "Which algorithm uses 'Memoization'?", options: ["Greedy", "Dynamic Programming", "Brute Force", "Divide and Conquer"], answer: 1 },
    { topic: "trees", question: "Complexity of finding an element in an AVL Tree?", options: ["O(n)", "O(log n)", "O(n^2)", "O(1)"], answer: 1 },
    { topic: "trees", question: "A complete binary tree has:", options: ["All levels full", "All levels full except possibly the last", "Only one child per node", "No children"], answer: 1 },
    { topic: "strings", question: "Huffman coding is used for:", options: ["Data Encryption", "Data Compression", "Data Transmission", "Data Storage"], answer: 1 },
    { topic: "complexity", question: "Which of these is NOT an asymptotic notation?", options: ["Big O", "Omega", "Theta", "Sigma"], answer: 3 },
    { topic: "graphs", question: "Bellman-Ford is better than Dijkstra's because:", options: ["It's faster", "It handles negative weights", "It uses less space", "It's simpler"], answer: 1 },
    { topic: "graphs", question: "Complexity of Floyd-Warshall algorithm:", options: ["O(V^3)", "O(V^2)", "O(E log V)", "O(VE)"], answer: 0 },
    { topic: "algorithms", question: "An 'external sort' is used when:", options: ["Data fits in RAM", "Data is too large for RAM", "Data is on a cloud server", "Data is encrypted"], answer: 1 },
    { topic: "stacks-queues", question: "The 'Rear' end of a Queue is used for:", options: ["Deletion", "Insertion", "Searching", "Updating"], answer: 1 },
    { topic: "strings", question: "What is a Trie used for?", options: ["Numbers", "Strings/Prefixes", "Geographic data", "Video files"], answer: 1 },
    { topic: "complexity", question: "Adding to the front of an Array takes:", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 1 },
    { topic: "algorithms", question: "Binary search uses a ____ approach:", options: ["Linear", "Jump", "Logarithmic", "Quadratic"], answer: 2 },
    { topic: "trees", question: "The depth of a node is:", options: ["Distance from leaf", "Distance from root", "Number of children", "Value inside"], answer: 1 },
    { topic: "trees", question: "Red-Black trees ensure height is no more than:", options: ["2 log(n+1)", "log n", "n/2", "n"], answer: 0 },
    { topic: "graphs", question: "Maximum number of edges in an undirected graph with n nodes:", options: ["n", "n^2", "n(n-1)/2", "2n"], answer: 2 },
    { topic: "trees", question: "Which sort is used for Top-k elements?", options: ["Merge Sort", "Heap Sort", "Insertion Sort", "Bubble Sort"], answer: 1 },
    { topic: "stacks-queues", question: "In a circular queue, when is it full?", options: ["front == rear", "rear + 1 == front", "front == 0", "rear == size-1"], answer: 1 },
    { topic: "graphs", question: "What is a 'sink' node in a graph?", options: ["In-degree is 0", "Out-degree is 0", "Isolated node", "Connected to all"], answer: 1 },
    { topic: "complexity", question: "Space complexity of Merge Sort:", options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"], answer: 2 },
    { topic: "graphs", question: "Which of these is used to detect loops in a graph?", options: ["BFS", "DFS", "Binary Search", "Heapify"], answer: 1 },
    { topic: "stacks-queues", question: "If 'front' and 'rear' of a queue are both -1, the queue is:", options: ["Full", "Empty", "One element", "Broken"], answer: 1 },
    { topic: "graphs", question: "Minimum number of nodes in a path between two nodes in a graph:", options: ["1", "0", "Distance", "Weight"], answer: 2 },
    { topic: "complexity", question: "Big O notation describes:", options: ["Average case", "Best case", "Worst case", "Constant time"], answer: 2 },
    { topic: "algorithms", question: "Which sort divides the array into 'sorted' and 'unsorted' portions?", options: ["Quick Sort", "Insertion Sort", "Merge Sort", "Tree Sort"], answer: 1 },
    { topic: "complexity", question: "What is a hash function that never has collisions called?", options: ["Perfect Hash", "Good Hash", "Linear Hash", "Fast Hash"], answer: 0 },
    { topic: "trees", question: "The 'degree' of a node in a tree is:", options: ["Number of ancestors", "Number of children", "Value / 2", "Total nodes in tree"], answer: 1 },
    { topic: "graphs", question: "Which algorithm finds the articulation points in a graph?", options: ["BFS", "Tarjan's", "Dijkstra's", "Prim's"], answer: 1 },
    { topic: "trees", question: "What is the time complexity of building a heap from an array?", options: ["O(n)", "O(n log n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "trees", question: "A Skip List is an alternative to:", options: ["Stack", "Hash Table", "Balanced Tree", "Queue"], answer: 2 },
    { topic: "algorithms", question: "Selection Sort works by:", options: ["Merging", "Finding min/max repeatedly", "Recursion", "Random swapping"], answer: 1 },
    { topic: "stacks-queues", question: "A priority queue is often used for:", options: ["Job scheduling", "Stack implementation", "Browser history", "Encryption"], answer: 0 },
    { topic: "complexity", question: "What is the space complexity of Depth First Search?", options: ["O(V)", "O(V^2)", "O(E)", "O(1)"], answer: 0 },
    { topic: "graphs", question: "Adjacency List is better for:", options: ["Dense Graphs", "Sparse Graphs", "Complete Graphs", "Disconnected Graphs"], answer: 1 },
    { topic: "trees", question: "How many nodes are in a full binary tree of height h?", options: ["2^h - 1", "2^(h+1) - 1", "log h", "h^2"], answer: 1 },
    { topic: "trees", question: "Worst-case of Binary Search Tree occurs when data is:", options: ["Random", "Sorted", "All same", "Prime"], answer: 1 },
    { topic: "stacks-queues", question: "A deque is:", options: ["Double-ended queue", "Deleted queue", "Dense queue", "Disconnected queue"], answer: 0 },
    { topic: "algorithms", question: "Bucket sort is efficient when input is:", options: ["Integer", "Uniformly distributed", "Small", "Sorted"], answer: 1 },
    { topic: "graphs", question: "Topological Sort is only for:", options: ["Undirected graphs", "Directed Acyclic Graphs (DAGs)", "Complete graphs", "Disconnected graphs"], answer: 1 },
    { topic: "trees", question: "Which traversal goes: Root, Left, Right?", options: ["In-order", "Pre-order", "Post-order", "Level-order"], answer: 1 },
    { topic: "trees", question: "Fenwick Tree is also known as:", options: ["Binary Indexed Tree", "Segment Tree", "AVL Tree", "Trie"], answer: 0 },
    { topic: "trees", question: "Segment Trees are used for:", options: ["String search", "Range queries", "Graph path", "Recursion"], answer: 1 },
    { topic: "algorithms", question: "Counting sort assumes input is in the range:", options: ["0 to n", "0 to k", "-inf to inf", "Unknown"], answer: 1 },
    { topic: "trees", question: "The time complexity of finding the diameter of a tree is:", options: ["O(V + E)", "O(V^2)", "O(log V)", "O(E log V)"], answer: 0 },
    { topic: "algorithms", question: "Which of these is a divide and conquer algorithm?", options: ["Bubble sort", "Quick sort", "Dijkstra's", "BFS"], answer: 1 },
    { topic: "trees", question: "Total nodes in a binary tree with 'L' leaves:", options: ["2L", "L+1", "2L-1", "Varies"], answer: 3 },
    { topic: "graphs", question: "A path with no repeated vertices is:", options: ["Cycle", "Simple Path", "Trail", "Walk"], answer: 1 },
    { topic: "algorithms", question: "Which sort is used in 'Timsort'?", options: ["Quick & Merge", "Merge & Insertion", "Heap & Selection", "Bubble & Radix"], answer: 1 },
    { topic: "graphs", question: "In Kruskal's, edges are processed in order of:", options: ["Index", "Increasing weight", "Decreasing weight", "Random"], answer: 1 },
    { topic: "graphs", question: "Complexity of Kruskal's Algorithm:", options: ["O(E log E)", "O(V^2)", "O(E + V)", "O(V log V)"], answer: 0 },

    // --- 101-200 (ARRAYS, STRINGS, ALGORITHMS, DP) ---
    { topic: "arrays", question: "In a 2D array a[m][n], the address of a[i][j] (row-major) is:", options: ["base + (i*n + j)*size", "base + (i*m + j)*size", "base + (j*n + i)*size", "base + i+j"], answer: 0 },
    { topic: "arrays", question: "An array with no elements is called:", options: ["Null array", "Empty array", "Sparse array", "Void array"], answer: 1 },
    { topic: "arrays", question: "The process of moving elements to fill a gap in an array is:", options: ["Shifting", "Swapping", "Merging", "Sorting"], answer: 0 },
    { topic: "complexity", question: "Amortized complexity of a dynamic array resize (doubling strategy):", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "arrays", question: "Finding the second largest element in an unsorted array takes:", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 2 },
    { topic: "complexity", question: "Time complexity of Kadane's algorithm:", options: ["O(n)", "O(n^2)", "O(log n)", "O(n log n)"], answer: 0 },
    { topic: "arrays", question: "Which principle does Kadane's algorithm use?", options: ["Greedy", "Dynamic Programming", "Recursion", "Backtracking"], answer: 1 },
    { topic: "complexity", question: "Space complexity of Kadane's algorithm:", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "arrays", question: "In which case is Kadane's algorithm used?", options: ["Finding max subarray sum", "Sorting", "Searching", "Graph traversal"], answer: 0 },
    { topic: "arrays", question: "What is the lower bound for comparison-based sorting?", options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], answer: 1 },
    { topic: "algorithms", question: "Which sorting algorithm performs best on nearly sorted data?", options: ["Quick Sort", "Insertion Sort", "Merge Sort", "Heap Sort"], answer: 1 },
    { topic: "algorithms", question: "Counting sort is effective only for:", options: ["Large range integers", "Floating point numbers", "Small range integers", "Strings"], answer: 2 },
    { topic: "algorithms", question: "Radix sort uses ____ as its subroutine:", options: ["Quick sort", "Merge sort", "Counting sort", "Selection sort"], answer: 2 },
    { topic: "complexity", question: "What is the time complexity of Radix Sort (where d is digits and k is base)?", options: ["O(d*(n+k))", "O(n log n)", "O(n^2)", "O(d*log n)"], answer: 0 },
    { topic: "algorithms", question: "In Heap Sort, the initial building of a max-heap takes:", options: ["O(n)", "O(n log n)", "O(log n)", "O(1)"], answer: 0 },
    { topic: "algorithms", question: "Which traversal is used during the building of a Heap?", options: ["Top-down", "Bottom-up", "Recursive random", "Left-to-right only"], answer: 1 },
    { topic: "algorithms", question: "Which sort is used for sorting linked lists?", options: ["Quick Sort", "Merge Sort", "Heap Sort", "Bubble Sort"], answer: 1 },
    { topic: "algorithms", question: "Complexity of Binary Search on a sorted array of size n:", options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"], answer: 0 },
    { topic: "algorithms", question: "Jump search complexity:", options: ["O(√n)", "O(log n)", "O(n)", "O(n log n)"], answer: 0 },
    { topic: "algorithms", question: "Interpolation search works best on:", options: ["Uniformly distributed data", "Skewed data", "Random data", "Sorted data"], answer: 0 },
    { topic: "complexity", question: "Worst case of Interpolation search:", options: ["O(n)", "O(log n)", "O(log log n)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Best case of Interpolation search:", options: ["O(1)", "O(log log n)", "O(log n)", "O(n)"], answer: 1 },
    { topic: "strings", question: "A suffix tree is a specialized version of:", options: ["Heap", "Trie", "Binary Tree", "Graph"], answer: 1 },
    { topic: "strings", question: "Which data structure is best for autocomplete features?", options: ["Heap", "Trie", "Array", "Stack"], answer: 1 },
    { topic: "strings", question: "Time complexity to search a pattern of length m in a Trie of total length N:", options: ["O(m)", "O(n)", "O(log n)", "O(N)"], answer: 0 },
    { topic: "strings", question: "Naïve pattern searching complexity (Text n, Pattern m):", options: ["O(m*n)", "O(m+n)", "O(n^2)", "O(m^2)"], answer: 0 },
    { topic: "strings", question: "Rabin-Karp uses ____ to speed up string matching:", options: ["Hashing", "Sorting", "Recursion", "Two pointers"], answer: 0 },
    { topic: "complexity", question: "Worst case of Rabin-Karp algorithm:", options: ["O(m*n)", "O(m+n)", "O(n log n)", "O(m)"], answer: 0 },
    { topic: "strings", question: "Knuth-Morris-Pratt (KMP) avoids redundant comparisons using:", options: ["LPS (Longest Proper Suffix) array", "Hashing", "Sorting", "Staring from end"], answer: 0 },
    { topic: "complexity", question: "Time complexity of KMP searching:", options: ["O(m+n)", "O(m*n)", "O(n^2)", "O(m)"], answer: 0 },
    { topic: "strings", question: "A palindrome is a string that:", options: ["Is very long", "Reads same backwards", "Has only vowels", "Has only consonants"], answer: 1 },
    { topic: "dp", question: "The classic approach for 'Longest Common Subsequence' is:", options: ["Greedy", "Dynamic Programming", "Divid and Conquer", "Backtracking"], answer: 1 },
    { topic: "complexity", question: "Time complexity of Matrix Chain Multiplication (n matrices):", options: ["O(n^3)", "O(n^2)", "O(2^n)", "O(n log n)"], answer: 0 },
    { topic: "dp", question: "0-1 Knapsack problem is solved optimally using:", options: ["Greedy", "Memoization / DP", "Sorting", "Random selection"], answer: 1 },
    { topic: "dp", question: "Fractional Knapsack problem is solved optimally using:", options: ["Greedy", "Dynamic Programming", "Recursion", "Searching"], answer: 0 },
    { topic: "dp", question: "What is 'Bottom-Up' DP also called?", options: ["Tabulation", "Memoization", "Greedy", "Iteration"], answer: 0 },
    { topic: "dp", question: "What is 'Top-Down' DP also called?", options: ["Tabulation", "Memoization", "Recursion", "Sorting"], answer: 1 },
    { topic: "dp", question: "Coin Change problem asks for:", options: ["Max coins for total", "Min coins for total", "Both", "Sorting coins"], answer: 1 },
    { topic: "dp", question: "Bellman-Ford uses which approach?", options: ["Greedy", "Dynamic Programming", "BFS", "DFS"], answer: 1 },
    { topic: "dp", question: "Floyd-Warshall is an example of:", options: ["All-pairs shortest path", "Single-source shortest path", "MST", "String matching"], answer: 0 },
    { topic: "linked-lists", question: "What is the time complexity of finding the middle element of a linked list in one pass?", options: ["O(n)", "O(n^2)", "O(log n)", "O(1)"], answer: 0 },
    { topic: "linked-lists", question: "Which algorithm uses 'slow' and 'fast' pointers to detect cycles?", options: ["Floyd's Cycle-Finding", "Dijkstra's", "Tarjan's", "KMP"], answer: 0 },
    { topic: "linked-lists", question: "In a linked list, each node contains data and ____:", options: ["Index", "Pointer to next", "Value / 2", "Previous value"], answer: 1 },
    { topic: "linked-lists", question: "A skip list is a ____ data structure:", options: ["Probabilistic", "Deterministic", "Static", "Binary"], answer: 0 },
    { topic: "complexity", question: "Average search complexity in a Skip List:", options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"], answer: 0 },
    { topic: "linked-lists", question: "Which linked list allows traversal in both directions?", options: ["Singly", "Doubly", "Circular", "None"], answer: 1 },
    { topic: "linked-lists", question: "Header node of a linked list simplifies:", options: ["Traversal", "Boundary cases (insertion/deletion)", "Memory usage", "Sorting speed"], answer: 1 },
    { topic: "linked-lists", question: "Memory allocated for linked list nodes is usually:", options: ["Static", "Dynamic (Heap)", "Stack based", "Cache only"], answer: 1 },
    { topic: "complexity", question: "Deleting a node at a given pointer in a singly linked list (given only the pointer) takes:", options: ["O(1) - copying data", "O(n)", "O(log n)", "O(V)"], answer: 0 },
    { topic: "linked-lists", question: "Which linked list consumes more memory?", options: ["Singly", "Doubly", "Circular Singly", "Array"], answer: 1 },
    { topic: "complexity", question: "Complexity of merging two sorted linked lists of size m and n:", options: ["O(m+n)", "O(m*n)", "O(log(m+n))", "O(1)"], answer: 0 },
    { topic: "stacks-queues", question: "Which structure is used for 'Undo' in text editors?", options: ["Queue", "Stack", "Tree", "Graph"], answer: 1 },
    { topic: "stacks-queues", question: "Which structure is used for 'Printer Spooling'?", options: ["Queue", "Stack", "Linked List", "Hash Table"], answer: 0 },
    { topic: "stacks-queues", question: "Priority queues are typically implemented with:", options: ["Stacks", "Heaps", "Hash Tables", "Arrays"], answer: 1 },
    { topic: "stacks-queues", question: "In a double-ended queue (deque), insertion/deletion is possible at:", options: ["Front only", "Rear only", "Both ends", "Middle only"], answer: 2 },
    { topic: "complexity", question: "Time complexity to evaluate a postfix expression of length n:", options: ["O(n)", "O(n^2)", "O(log n)", "O(2^n)"], answer: 0 },
    { topic: "complexity", question: "Time complexity to convert infix to postfix:", options: ["O(n)", "O(n^2)", "O(log n)", "O(1)"], answer: 0 },
    { topic: "stacks-queues", question: "Which notation is also called Reverse Polish Notation?", options: ["Infix", "Prefix", "Postfix", "Polish"], answer: 2 },
    { topic: "stacks-queues", question: "A stack overflow occurs when:", options: ["Stack is empty", "Stack is full", "Stack is sorted", "Stack is reversed"], answer: 1 },
    { topic: "stacks-queues", question: "Function calls are handled by which memory segment?", options: ["Heap", "Stack", "Data", "Code"], answer: 1 },
    { topic: "trees", question: "A Binary Tree where every node has 0 or 2 children is:", options: ["Perfect", "Complete", "Full", "Skewed"], answer: 2 },
    { topic: "trees", question: "A Binary Tree where all levels are full is:", options: ["Perfect", "Complete", "Full", "B-Tree"], answer: 0 },
    { topic: "trees", question: "Maximum nodes in a binary tree of height h (root at level 0):", options: ["2^(h+1) - 1", "2^h - 1", "log h", "h^2"], answer: 0 },
    { topic: "trees", question: "In a Binary Search Tree, the left child is always:", options: ["Greater than root", "Less than root", "Equal to root", "Same as right"], answer: 1 },
    { topic: "complexity", question: "Worst case search complexity in an AVL tree:", options: ["O(log n)", "O(n)", "O(n log n)", "O(1)"], answer: 0 },
    { topic: "trees", question: "AVL trees are named after:", options: ["Adelson-Velsky and Landis", "A.V. Lucas", "Alpha Vanilla Lambda", "A Very Large tree"], answer: 0 },
    { topic: "trees", question: "Red-Black trees use ____ for balancing:", options: ["Rotations and Color flips", "Only rotations", "Re-insertion", "Sorting"], answer: 0 },
    { topic: "complexity", question: "Worst case search in a Red-Black tree:", options: ["O(log n)", "O(n)", "O(n log n)", "O(√n)"], answer: 0 },
    { topic: "trees", question: "Which self-balancing tree is frequently used in Java's TreeMap?", options: ["AVL Tree", "Red-Black Tree", "Splay Tree", "B-Tree"], answer: 1 },
    { topic: "trees", question: "A Splay Tree moves the recently accessed element to root using:", options: ["Color flips", "Splaying (rotations)", "Deletion", "Swapping"], answer: 1 },
    { topic: "trees", question: "B-Tree of order m can have at most how many children?", options: ["m", "m-1", "m/2", "2m"], answer: 0 },
    { topic: "trees", question: "Where is data stored in a B+ Tree?", options: ["Internal nodes", "Leaf nodes", "Both", "Root only"], answer: 1 },
    { topic: "trees", question: "Threaded Binary Tree uses ____ for faster traversal:", options: ["Recursion", "NULL pointers transformed into links", "Heaps", "Arrays"], answer: 1 },
    { topic: "trees", question: "In a Min-Heap, the root element is always:", options: ["Smallest", "Largest", "Zero", "Random"], answer: 0 },
    { topic: "complexity", question: "Complexity of extract-min in a Binary Heap of size n:", options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"], answer: 0 },
    { topic: "trees", question: "Priority Queues are most efficiently implemented using:", options: ["Linked list", "Binary Search Tree", "Heap", "Stack"], answer: 2 },
    { topic: "complexity", question: "Finding the kth largest element using a Min-Heap of size k takes:", options: ["O(n log k)", "O(n log n)", "O(n)", "O(k log n)"], answer: 0 },
    { topic: "graphs", question: "Which traversal finds the shortest path in an unweighted graph?", options: ["BFS", "DFS", "Dijkstra's", "A*"], answer: 0 },
    { topic: "graphs", question: "Which traversal uses more memory for deep graphs?", options: ["BFS", "DFS", "Binary Search", "All same"], answer: 0 },
    { topic: "complexity", question: "Space complexity of BFS (V vertices, E edges) using adjacency list:", options: ["O(V)", "O(V+E)", "O(E)", "O(V^2)"], answer: 0 },
    { topic: "complexity", question: "Time complexity of DFS using adjacency list:", options: ["O(V+E)", "O(V^2)", "O(V*E)", "O(log V)"], answer: 0 },
    { topic: "graphs", question: "A graph is bipartite if its vertices can be colored using:", options: ["1 color", "2 colors", "3 colors", "V colors"], answer: 1 },
    { topic: "graphs", question: "A cycle that visits every edge exactly once is:", options: ["Hamiltonian", "Eulerian", "Simple", "Complete"], answer: 1 },
    { topic: "graphs", question: "A cycle that visits every vertex exactly once is:", options: ["Hamiltonian", "Eulerian", "Simple", "Star"], answer: 0 },
    { topic: "graphs", question: "Kahn's algorithm is used for:", options: ["Shortest path", "Topological Sort", "MST", "Loop detection"], answer: 1 },
    { topic: "graphs", question: "Strongly Connected Components exist only in:", options: ["Undirected graphs", "Directed graphs", "Acyclic graphs", "Balanced trees"], answer: 1 },
    { topic: "graphs", question: "Kruskal's algorithm uses which data structure?", options: ["Disjoint Set Union (DSU)", "Stack", "Queue", "Hash Table"], answer: 0 },
    { topic: "complexity", question: "Worst case time complexity of Dijkstra's using a Fibonacci Heap:", options: ["O(E + V log V)", "O(E log V)", "O(V^2)", "O(E*V)"], answer: 0 },
    { topic: "complexity", question: "Dijkstra's algorithm fails for graphs with:", options: ["Cycles", "Negative edge weights", "Multiple sources", "Weighted edges"], answer: 1 },
    { topic: "graphs", question: "A self-loop in a graph is an edge that:", options: ["Connects to neighbor", "Connects to itself", "Is very long", "Is negative"], answer: 1 },
    { topic: "complexity", question: "Complexity of building a Segment Tree of size n:", options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Query complexity in a Fenwick Tree (BIT):", options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"], answer: 0 },
    { topic: "complexity", question: "Space complexity of a Segment Tree:", options: ["O(n)", "O(log n)", "O(V)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Complexity of sorting an array of n strings each of length L:", options: ["O(n log n * L)", "O(n log n)", "O(L log n)", "O(n*L)"], answer: 0 },
    { topic: "complexity", question: "Finding an element in a sorted matrix of size N x N takes:", options: ["O(N)", "O(N^2)", "O(log N)", "O(1)"], answer: 0 },
    { topic: "algorithms", question: "Which algorithm uses the 'divide and conquer' principle?", options: ["Binary Search", "Selection Sort", "Linear Search", "Jump Search"], answer: 0 },
    { topic: "complexity", question: "Complexity of Big-O(1):", options: ["Constant", "Linear", "Logarithmic", "Exponential"], answer: 0 },
    { topic: "complexity", question: "Complexity of Big-O(n!):", options: ["Factorial", "Logarithmic", "Quadratic", "Polynomial"], answer: 0 },
    { topic: "complexity", question: "What is the average case complexity of searching in a Hash Table?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Deleting a node in a balanced BST takes:", options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"], answer: 0 },

    // --- 201-300 (Specialized, Adv DP, Adv Graphs, Strings, Complexity) ---
    { topic: "dp", question: "The 'Optimal Substructure' property means:", options: ["Problem is easy", "Optimal solution contains optimal solutions to subproblems", "Problem is greedy", "Solution is constant"], answer: 1 },
    { topic: "dp", question: "The 'Overlapping Subproblems' property means:", options: ["Subproblems are independent", "Same subproblems are solved multiple times", "No subproblems", "Memory overflow"], answer: 1 },
    { topic: "dp", question: "Longest Increasing Subsequence (LIS) complexity (O(n log n) version):", options: ["O(n log n)", "O(n^2)", "O(n)", "O(2^n)"], answer: 0 },
    { topic: "dp", question: "Edit Distance problem (Levenshtein) complexity:", options: ["O(m*n)", "O(m+n)", "O(m^n)", "O(1)"], answer: 0 },
    { topic: "dp", question: "Manacher’s Algorithm is used for:", options: ["Shortest path", "Longest Palindromic Substring", "Sorting", "Complexity"], answer: 1 },
    { topic: "complexity", question: "Complexity of Manacher's Algorithm:", options: ["O(n)", "O(n^2)", "O(n log n)", "O(1)"], answer: 0 },
    { topic: "strings", question: "Z-algorithm is used for:", options: ["String matching", "Sorting", "Graphs", "DP"], answer: 0 },
    { topic: "complexity", question: "Complexity of Z-algorithm:", options: ["O(n)", "O(n^2)", "O(log n)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Burrows-Wheeler Transform is used in:", options: ["Sorting", "Compression", "Encryption", "Searching"], answer: 1 },
    { topic: "graphs", question: "A graph is connected if:", options: ["It has a cycle", "There is a path between every two vertices", "It is complete", "It is tree"], answer: 1 },
    { topic: "graphs", question: "A tree with n vertices has how many edges?", options: ["n", "n-1", "n+1", "n^2"], answer: 1 },
    { topic: "graphs", question: "Which algorithm finds all pairs shortest path in a graph with negative weights?", options: ["Dijkstra's", "Floyd-Warshall", "Prim's", "Kruskal's"], answer: 1 },
    { topic: "graphs", question: "Dijkstra's can be viewed as a ____ algorithm:", options: ["Greedy", "DP", "Random", "Brute Force"], answer: 0 },
    { topic: "graphs", question: "Maximum flow in a network is equal to:", options: ["Min-cut value", "Max-cut value", "Average flow", "Zero"], answer: 0 },
    { topic: "graphs", question: "Edmonds-Karp is an implementation of:", options: ["Dijkstra's", "Ford-Fulkerson", "MST", "DFS"], answer: 1 },
    { topic: "complexity", question: "Complexity of Edmonds-Karp:", options: ["O(VE^2)", "O(V^3)", "O(E log V)", "O(VE)"], answer: 0 },
    { topic: "graphs", question: "Dinics algorithm is used for:", options: ["Shortest path", "Max Flow", "Sorting", "Searching"], answer: 1 },
    { topic: "graphs", question: "A DAG (Directed Acyclic Graph) can always be:", options: ["Sorted topologically", "Flattened", "Combined", "Deleted"], answer: 0 },
    { topic: "graphs", question: "Checking if a graph is cyclic using DSU takes (nearly):", options: ["O(E)", "O(V)", "O(V log V)", "O(1)"], answer: 0 },
    { topic: "graphs", question: "Which algorithm finds the center of a tree?", options: ["DFS/BFS by removing leaves", "Dijkstra's", "Prim's", "Kruskal's"], answer: 0 },
    { topic: "trees", question: "Lowest Common Ancestor (LCA) in a tree can be found in:", options: ["O(log n) after preprocessing", "O(n)", "O(1)", "O(n^2)"], answer: 0 },
    { topic: "trees", question: "Heavy-Light Decomposition is used to:", options: ["Balance trees", "Query paths in trees", "Sort trees", "Delete trees"], answer: 1 },
    { topic: "trees", question: "A Centroid of a tree is a vertex whose removal split tree into components of size <=:", options: ["n/2", "n/4", "log n", "1"], answer: 0 },
    { topic: "complexity", question: "Sparse Table is useful for:", options: ["Range Minimum Query (RMQ)", "Sorting", "Hashing", "Encryption"], answer: 0 },
    { topic: "complexity", question: "Preprocessing time for a Sparse Table:", options: ["O(n log n)", "O(n)", "O(1)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Query time for a Sparse Table (for idempotent functions like min):", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0 },
    { topic: "complexity", question: "What is an in-memory hash table collision resolution strategy?", options: ["Chaining", "Linear Probing", "Both", "Sorting"], answer: 2 },
    { topic: "complexity", question: "Double hashing reduces:", options: ["Clustering", "Memory", "Speed", "Cycles"], answer: 0 },
    { topic: "complexity", question: "What is the worst case complexity of searching in a hash table with chaining?", options: ["O(n)", "O(1)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Dynamic programming approach for Fibonacci takes ____ space (optimized):", options: ["O(1)", "O(n)", "O(log n)", "O(2^n)"], answer: 0 },
    { topic: "dp", question: "The Traveling Salesperson Problem (TSP) is solved using DP (Held-Karp) in:", options: ["O(n^2 * 2^n)", "O(n!)", "O(n^3)", "O(n log n)"], answer: 0 },
    { topic: "dp", question: "DP on broken profile (bitmask DP) is used for:", options: ["Tiling problems", "Sorting", "Searching", "Graphs"], answer: 0 },
    { topic: "dp", question: "The word 'Programming' in Dynamic Programming means:", options: ["Coding", "Tabular solution / Planning", "Binary logic", "Advanced math"], answer: 1 },
    { topic: "algorithms", question: "Stooge Sort has a complexity of:", options: ["O(n^2.7)", "O(n log n)", "O(n^2)", "O(n)"], answer: 0 },
    { topic: "algorithms", question: "Bogosort is a ____ sort:", options: ["Highly efficient", "Inefficient random", "Stable", "Recursive"], answer: 1 },
    { topic: "algorithms", question: "Complexity of Sleep Sort (conceptually):", options: ["O(max(input))", "O(n log n)", "O(1)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Space complexity of QuickSort in the worst case (stack depth):", options: ["O(n)", "O(log n)", "O(1)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Which notation represents the 'tightest' bound?", options: ["Theta", "Big O", "Omega", "Little o"], answer: 0 },
    { topic: "complexity", question: "Which sort is used for sorting integers in 0 to n^2-1?", options: ["Radix Sort in O(n)", "Merge Sort", "Quick Sort", "Bubble Sort"], answer: 0 },
    { topic: "complexity", question: "Linear search is better than Binary search for ____:", options: ["Unsorted/Small data", "Sorted large data", "Circular data", "Encrypted data"], answer: 0 },
    { topic: "complexity", question: "Binary search on a linked list takes:", options: ["O(n)", "O(log n)", "O(1)", "O(n log n)"], answer: 0 },
    { topic: "linked-lists", question: "Self-organizing list moves frequently accessed items to:", options: ["Front", "Rear", "Middle", "Random"], answer: 0 },
    { topic: "stacks-queues", question: "Implement a queue using two stacks. Cost of enqueue (amortized):", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "stacks-queues", question: "Which data structure is used to convert infix to prefix?", options: ["Stack", "Queue", "Tree", "Graph"], answer: 0 },
    { topic: "trees", question: "Is every binary tree a heap?", options: ["No, must satisfy heap property", "Yes", "Only if it is complete", "Only if it is balanced"], answer: 0 },
    { topic: "trees", question: "Is every binary search tree an AVL tree?", options: ["No, only if balanced", "Yes", "Only if complete", "Only if sorted"], answer: 0 },
    { topic: "trees", question: "Number of binary trees with 3 nodes:", options: ["5", "3", "4", "2"], answer: 0 },
    { topic: "complexity", question: "Catalan numbers are used to count:", options: ["Binary Trees", "Graphs", "Linked Lists", "Arrays"], answer: 0 },
    { topic: "trees", question: "In-order successor of a node in a BST is:", options: ["Min of right subtree", "Max of left subtree", "Root", "Parent"], answer: 0 },
    { topic: "trees", question: "In-order predecessor of a node in a BST is:", options: ["Max of left subtree", "Min of right subtree", "Root", "Parent"], answer: 0 },
    { topic: "trees", question: "Maximum height of a Red-Black tree with n nodes:", options: ["2 log2(n+1)", "log2 n", "1.44 log2 n", "n"], answer: 0 },
    { topic: "trees", question: "Level-order traversal is also known as:", options: ["Breadth-First Search (BFS)", "Depth-First Search (DFS)", "In-order", "Pre-order"], answer: 0 },
    { topic: "graphs", question: "Diameter of a graph is:", options: ["Maximum of all shortest paths", "Length of cycle", "Number of edges", "Total vertices"], answer: 0 },
    { topic: "graphs", question: "A graph with no vertices and no edges is:", options: ["Null graph", "Complete graph", "Bipartite", "Tree"], answer: 0 },
    { topic: "graphs", question: "What is the maximum number of components in a graph with V vertices?", options: ["V", "1", "V-1", "V/2"], answer: 0 },
    { topic: "graphs", question: "Prim’s algorithm is based on:", options: ["Greedy approach", "DP approach", "Backtracking", "Divide and conquer"], answer: 0 },
    { topic: "graphs", question: "Difference between Prim’s and Kruskal’s:", options: ["Prim's grows a tree, Kruskal's merges forests", "Prim's is slower", "Kruskal's is for directed", "No difference"], answer: 0 },
    { topic: "graphs", question: "Minimum edges to connect V vertices:", options: ["V-1", "V", "V+1", "log V"], answer: 0 },
    { topic: "graphs", question: "Algorithm for finding bridges in a graph:", options: ["Tarjan's", "Dijkstra's", "BFS", "Prim's"], answer: 0 },
    { topic: "graphs", question: "Maximum degree of a vertex in an n-vertex simple graph:", options: ["n-1", "n", "n^2", "1"], answer: 0 },
    { topic: "complexity", question: "Complexity of an algorithm that doubles its input work each step (n steps):", options: ["O(2^n)", "O(n^2)", "O(n log n)", "O(n)"], answer: 0 },
    { topic: "complexity", question: "P vs NP question deals with:", options: ["Efficiency of solutions vs verification", "Sorting", "Graphic designs", "Memory segments"], answer: 0 },
    { topic: "complexity", question: "NP-complete problems have:", options: ["No known polynomial time solution", "O(1) solution", "Negative weights always", "Only one node"], answer: 0 },
    { topic: "complexity", question: "Space complexity of building a balanced BST from a sorted array:", options: ["O(log n) - stack space", "O(1)", "O(n)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Worst case of Selection Sort occurs when:", options: ["Data is reversed (actually always n^2)", "Data is sorted", "Data is random", "Data is small"], answer: 0 },
    { topic: "complexity", question: "What is the complexity of an empty loop for(int i=0; i<n; i++);?", options: ["O(n)", "O(1)", "O(n^2)", "O(0)"], answer: 0 },
    { topic: "complexity", question: "Time complexity of T(n) = T(n/2) + c:", options: ["O(log n)", "O(n)", "O(n log n)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Time complexity of T(n) = 2T(n/2) + n:", options: ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], answer: 0 },
    { topic: "complexity", question: "Master Theorem provides solutions for:", options: ["Recurrence relations", "Sorting", "Hashing", "Encryption"], answer: 0 },
    { topic: "linked-lists", question: "Which is efficiently done in LL over Array?", options: ["Insertion in middle", "Random Access", "Binary search", "Cache locality"], answer: 0 },
    { topic: "linked-lists", question: "Copy on Write (COW) is used for:", options: ["Memory optimization", "Sorting", "Searching", "Graph path"], answer: 0 },
    { topic: "stacks-queues", question: "A Queue becomes full when (normal implementation):", options: ["rear == size-1", "front == 0", "rear == front", "count == 0"], answer: 0 },
    { topic: "stacks-queues", question: "Priority queues in operating systems are for:", options: ["Process scheduling", "Booting", "Typing", "Displaying pixels"], answer: 0 },
    { topic: "strings", question: "Longest Repeating Subsequence uses:", options: ["LCS of string with itself", "Sorting", "Searching", "Hashing"], answer: 0 },
    { topic: "dp", question: "Floyd-Warshall logic: dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]) where k is:", options: ["Intermediate vertex", "Final vertex", "Root", "Neighbor"], answer: 0 },
    { topic: "graphs", question: "Minimum number of colors for a tree:", options: ["2", "1", "3", "V"], answer: 0 },
    { topic: "graphs", question: "Minimum number of colors for a planar graph:", options: ["4", "5", "3", "2"], answer: 0 },
    { topic: "graphs", question: "A graph is a forest if it is:", options: ["A collection of trees", "Very big", "Cyclic", "Directed"], answer: 0 },
    { topic: "graphs", question: "Degree of a vertex in regular graph of degree k:", options: ["k", "k-1", "k+1", "1"], answer: 0 },
    { topic: "complexity", question: "Space complexity of an adjacency matrix for V vertices:", options: ["O(V^2)", "O(V)", "O(E)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Time complexity of swapping two variables without third (a=a+b...):", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Space complexity to store a binary tree with n nodes using pointers:", options: ["O(n)", "O(log n)", "O(1)", "O(n^2)"], answer: 0 },
    { topic: "complexity", question: "Worst case of merge sort space is due to:", options: ["Auxiliary array", "Depth of recursion", "Comparisons", "Value size"], answer: 0 },
    { topic: "complexity", question: "Is O(n^2) included in O(n^3)?", options: ["Yes", "No", "Only if n is large", "Only if n is small"], answer: 0 },
    { topic: "complexity", question: "Best case complexity of Bubble Sort (with flag):", options: ["O(n)", "O(n log n)", "O(n^2)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Worst case of Insertion Sort occurs when:", options: ["Array is sorted in reverse", "Array is already sorted", "Array is random", "Array is small"], answer: 0 },
    { topic: "complexity", question: "Which sorting algorithm is in-place?", options: ["Quick Sort", "Merge Sort", "Counting Sort", "Radix Sort"], answer: 0 },
    { topic: "trees", question: "Number of edges in a complete binary tree with n nodes:", options: ["n-1", "n", "n+1", "2n"], answer: 0 },
    { topic: "complexity", question: "How many subproblems for LCS of two strings length n and m?", options: ["n*m", "n+m", "2^n", "n!"], answer: 0 },
    { topic: "complexity", question: "Fibonacci in DP O(n) is faster than recursion O(2^n) because of:", options: ["Eliminating redundant calculations", "Binary logic", "Large memory", "Iterative speed"], answer: 0 },
    { topic: "complexity", question: "Which algorithm is used in Git to detect differences?", options: ["LCS", "Sorting", "Hashing", "Graphs"], answer: 0 },
    { topic: "complexity", question: "A Bloom Filter is used to check:", options: ["Set membership (with false positives)", "Sorting", "Merging", "Encryption"], answer: 0 },
    { topic: "complexity", question: "Bloom Filter never returns:", options: ["False negatives", "False positives", "Correct results", "Null"], answer: 0 },
    { topic: "complexity", question: "Optimal storage of a sparse matrix:", options: ["Coordinate list (COO) or CSR", "Normal array", "Stack", "Queue"], answer: 0 },
    { topic: "complexity", question: "Searching in a skip list with 2 levels:", options: ["O(n/2 + 2)", "O(log n)", "O(n)", "O(1)"], answer: 0 },
    { topic: "complexity", question: "Recursive binary search uses ____ space:", options: ["O(log n)", "O(1)", "O(n)", "O(n log n)"], answer: 0 },
    { topic: "complexity", question: "Iterative binary search uses ____ space:", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0 },
    { topic: "complexity", question: "Stable sort maintains relative order of:", options: ["Equal elements", "Different elements", "All elements", "Large elements"], answer: 0 },
    { topic: "complexity", question: "Worst case time for a heap insert:", options: ["O(log n)", "O(1)", "O(n)", "O(n log n)"], answer: 0 },
    { topic: "complexity", question: "Number of rotations in Red-Black insert (worst case):", options: ["2", "Unlimited", "log n", "n"], answer: 0 }
];
